on: 
  push: 
    branches:
      - release
  pull_request:
    branches:
      - release

name: Build Nuget
jobs:
  install:
    name: Install    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - name: Install Credential Provider
      run:
        export PATH="$PATH:/root/.dotnet/tools"
        dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
        dotnet codeartifact-creds install
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore ./src/
    - name: Build Configuration
      run: dotnet build --configuration Release --no-restore ./src/
        
  test:
    name: Test   
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./src/JaVisitei.Brasil.Test
      
  build:
    name: Build  
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.AWS_ARN_IAM_ROLE }}
        role-duration-seconds: 1200
        aws-region: us-east-1
  
    - name: Build and publish
      run: |
        export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ${{ secrets.AWS_DOMAIN }} --domain-owner ${{ secrets.AWS_OWNER }} --query authorizationToken --output text`
        dotnet nuget add source ${{ secrets.AWS_PACKAGE }} -n ${{ secrets.AWS_DOMAIN }}/${{ secrets.AWS_REPOSITORY }} -u "aws" -p "${CODEARTIFACT_AUTH_TOKEN}" --store-password-in-clear-text
     #   dotnet build .
        
    - name: List Package
      run: aws codeartifact list-packages --domain ${{ secrets.AWS_DOMAIN }} --domain-owner ${{ secrets.AWS_OWNER }} --repository ${{ secrets.AWS_REPOSITORY }}

    - name: build pack
      run: |
        dotnet pack -o .
        dotnet nuget push *.nupkg -s codeartifact
        
    - name: List Package
      run: aws codeartifact list-packages --domain ${{ secrets.AWS_DOMAIN }} --domain-owner ${{ secrets.AWS_OWNER }} --repository ${{ secrets.AWS_REPOSITORY }}
