name: Pipeline Nuget

on: 
  push: 
    branches:
      - release
  pull_request:
    branches:
      - release
  
jobs:
  build:
    name: Build    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore ./src/JaVisitei.Brasil.Nuget

    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/JaVisitei.Brasil.Nuget

    - name: Tests
      run: dotnet test --no-restore --verbosity normal ./src/JaVisitei.Brasil.Test

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: deploy-package.zip
        path: ./src/JaVisitei.Brasil.Nuget/bin/Release/

  deploy:
    name: Deploy  
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.AWS_ARN_IAM_ROLE }}
        role-duration-seconds: 1200
        aws-region: us-east-1
      
    - name: Download artifact  
      uses: actions/download-artifact@v2
      with:
        name: deploy-package.zip
        path: ./src/JaVisitei.Brasil.Nuget/bin/Release/
        
    - name: Deploy
      run: |
        export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ${{ secrets.AWS_DOMAIN }} --domain-owner ${{ secrets.AWS_OWNER }} --query authorizationToken --output text`
        dotnet nuget add source ${{ secrets.AWS_PACKAGE }} -n ${{ secrets.AWS_DOMAIN }}/${{ secrets.AWS_REPOSITORY }} -u ${{ secrets.AWS_USER }} -p "${CODEARTIFACT_AUTH_TOKEN}" --store-password-in-clear-text
        
    - name: Publish
      run: |
        aws codeartifact delete-package-versions --domain ${{ secrets.AWS_DOMAIN }} --domain-owner ${{ secrets.AWS_OWNER }} --repository ${{ secrets.AWS_REPOSITORY }} --format nuget --package javisitei.brasil.nuget --versions 1.0.*
        dotnet nuget push ./src/JaVisitei.Brasil.Nuget/bin/Release/JaVisitei.Brasil.Nuget.1.0.0.nupkg --source ${{ secrets.AWS_DOMAIN }}/${{ secrets.AWS_REPOSITORY }}
        aws codeartifact list-packages --domain ${{ secrets.AWS_DOMAIN }} --domain-owner ${{ secrets.AWS_OWNER }} --repository ${{ secrets.AWS_REPOSITORY }}
        